# Generated by Django 3.2.8 on 2021-11-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211107_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/media/products_images/default.png', upload_to='products', verbose_name='Изображение'),
        ),
    ]
