# Generated by Django 3.2.8 on 2021-11-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/products_images/default.png', upload_to='products', verbose_name='Изображение'),
        ),
    ]
