# Generated by Django 3.2.8 on 2021-11-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-is_active',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
