# Generated by Django 3.2.8 on 2021-11-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='avatar',
            field=models.ImageField(blank=True, default='/media/users_avatars/default.jpg', upload_to='users_avatars', verbose_name='Аватар'),
        ),
    ]
