# Generated by Django 3.2.8 on 2021-11-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ('-is_active',)},
        ),
    ]
