# Generated by Django 3.2.9 on 2021-11-22 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from authapp.models import ShopUser, ShopUserProfile


def create_user_profile(apps, schema_editor):
    users = ShopUser.objects.all()
    for user in users:
        if not user.shopuserprofile:
            ShopUserProfile.objects.create(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0005_auto_20211118_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=128, verbose_name='Теги')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
                ('gender', models.CharField(choices=[('M', 'Мужчина'), ('W', 'Женщина'), ('O', 'Иные')], default='O',
                                            max_length=1, verbose_name='Пол')),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),

        migrations.RunPython(create_user_profile)
    ]
