# Generated by Django 3.2.8 on 2021-11-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_alter_shopuser_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopuser',
            options={'ordering': ('-is_superuser', '-is_active')},
        ),
    ]
